//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K8047CsDemoApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExitAlways {
            get {
                return ((bool)(this["ExitAlways"]));
            }
            set {
                this["ExitAlways"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartUsMinimized {
            get {
                return ((bool)(this["StartUsMinimized"]));
            }
            set {
                this["StartUsMinimized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowUsInTaskbarWhenMinimized {
            get {
                return ((bool)(this["ShowUsInTaskbarWhenMinimized"]));
            }
            set {
                this["ShowUsInTaskbarWhenMinimized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowUsInTaskbarWhenNormal {
            get {
                return ((bool)(this["ShowUsInTaskbarWhenNormal"]));
            }
            set {
                this["ShowUsInTaskbarWhenNormal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowSystemTrayNotifyIcon {
            get {
                return ((bool)(this["ShowSystemTrayNotifyIcon"]));
            }
            set {
                this["ShowSystemTrayNotifyIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExitWarningMessageBoxIsDisplayed {
            get {
                return ((bool)(this["ExitWarningMessageBoxIsDisplayed"]));
            }
            set {
                this["ExitWarningMessageBoxIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartUsTotallyInvisible {
            get {
                return ((bool)(this["StartUsTotallyInvisible"]));
            }
            set {
                this["StartUsTotallyInvisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotifyIconMouseDoubleLeftClickShowsForm1 {
            get {
                return ((bool)(this["NotifyIconMouseDoubleLeftClickShowsForm1"]));
            }
            set {
                this["NotifyIconMouseDoubleLeftClickShowsForm1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotifyIconMouseDoubleRightClickShowsForm1 {
            get {
                return ((bool)(this["NotifyIconMouseDoubleRightClickShowsForm1"]));
            }
            set {
                this["NotifyIconMouseDoubleRightClickShowsForm1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NotifyIconMouseSingleRightClickDisabled {
            get {
                return ((bool)(this["NotifyIconMouseSingleRightClickDisabled"]));
            }
            set {
                this["NotifyIconMouseSingleRightClickDisabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotifyIconMouseDoubleLeftClickShowsContextMenuStrip {
            get {
                return ((bool)(this["NotifyIconMouseDoubleLeftClickShowsContextMenuStrip"]));
            }
            set {
                this["NotifyIconMouseDoubleLeftClickShowsContextMenuStrip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotifyIconMouseDoubleRightClickShowsContextMenuStrip {
            get {
                return ((bool)(this["NotifyIconMouseDoubleRightClickShowsContextMenuStrip"]));
            }
            set {
                this["NotifyIconMouseDoubleRightClickShowsContextMenuStrip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NotifyIconMouseSingleLeftClickShowsContextMenuStrip {
            get {
                return ((bool)(this["NotifyIconMouseSingleLeftClickShowsContextMenuStrip"]));
            }
            set {
                this["NotifyIconMouseSingleLeftClickShowsContextMenuStrip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotifyIconMouseSingleLeftClickUsesDifferentContextMenuStrip {
            get {
                return ((bool)(this["NotifyIconMouseSingleLeftClickUsesDifferentContextMenuStrip"]));
            }
            set {
                this["NotifyIconMouseSingleLeftClickUsesDifferentContextMenuStrip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotifyIconMouseSingleLeftClickShowsForm1 {
            get {
                return ((bool)(this["NotifyIconMouseSingleLeftClickShowsForm1"]));
            }
            set {
                this["NotifyIconMouseSingleLeftClickShowsForm1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NotifyIconMouseSingleRightClickShowsForm1 {
            get {
                return ((bool)(this["NotifyIconMouseSingleRightClickShowsForm1"]));
            }
            set {
                this["NotifyIconMouseSingleRightClickShowsForm1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Form1MouseSingleRightClickDisabled {
            get {
                return ((bool)(this["Form1MouseSingleRightClickDisabled"]));
            }
            set {
                this["Form1MouseSingleRightClickDisabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Form1MouseSingleLeftClickUsesDifferentContextMenuStrip {
            get {
                return ((bool)(this["Form1MouseSingleLeftClickUsesDifferentContextMenuStrip"]));
            }
            set {
                this["Form1MouseSingleLeftClickUsesDifferentContextMenuStrip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Form1MouseSingleRightClickMinimizesForm1 {
            get {
                return ((bool)(this["Form1MouseSingleRightClickMinimizesForm1"]));
            }
            set {
                this["Form1MouseSingleRightClickMinimizesForm1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Form1MouseSingleLeftClickShowsContextMenuStrip {
            get {
                return ((bool)(this["Form1MouseSingleLeftClickShowsContextMenuStrip"]));
            }
            set {
                this["Form1MouseSingleLeftClickShowsContextMenuStrip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Form1MouseSingleLeftClickMinimizesForm1 {
            get {
                return ((bool)(this["Form1MouseSingleLeftClickMinimizesForm1"]));
            }
            set {
                this["Form1MouseSingleLeftClickMinimizesForm1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Form1MouseDoubleLeftClickShowsContextMenuStrip {
            get {
                return ((bool)(this["Form1MouseDoubleLeftClickShowsContextMenuStrip"]));
            }
            set {
                this["Form1MouseDoubleLeftClickShowsContextMenuStrip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Form1MouseDoubleLeftClickMinimizesForm1 {
            get {
                return ((bool)(this["Form1MouseDoubleLeftClickMinimizesForm1"]));
            }
            set {
                this["Form1MouseDoubleLeftClickMinimizesForm1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Form1MouseDoubleRightClickShowsContextMenuStrip {
            get {
                return ((bool)(this["Form1MouseDoubleRightClickShowsContextMenuStrip"]));
            }
            set {
                this["Form1MouseDoubleRightClickShowsContextMenuStrip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Form1MouseDoubleRightClickMinimizesForm1 {
            get {
                return ((bool)(this["Form1MouseDoubleRightClickMinimizesForm1"]));
            }
            set {
                this["Form1MouseDoubleRightClickMinimizesForm1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartUsSingleInstanceOnly {
            get {
                return ((bool)(this["StartUsSingleInstanceOnly"]));
            }
            set {
                this["StartUsSingleInstanceOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExitWarningBalloonTipIsDisplayed {
            get {
                return ((bool)(this["ExitWarningBalloonTipIsDisplayed"]));
            }
            set {
                this["ExitWarningBalloonTipIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int ExitWarningBalloonTipIsDisplayedForThisManyMilliseconds {
            get {
                return ((int)(this["ExitWarningBalloonTipIsDisplayedForThisManyMilliseconds"]));
            }
            set {
                this["ExitWarningBalloonTipIsDisplayedForThisManyMilliseconds"] = value;
            }
        }
    }
}
